[package]
authors = ["Jorge Aparicio <japaricious@gmail.com>"]
description = "A heap allocator for Cortex-M processors"
documentation = "https://docs.rs/alloc-cortex-m"
keywords = ["arm", "cortex-m", "allocator"]
license = "MIT OR Apache-2.0"
name = "alloc-cortex-m"
version = "0.1.0"

[dependencies]
cortex-m = "0.1.5"

[dependencies.linked_list_allocator]
branch = "init"
git = "https://github.com/japaric/linked-list-allocator"
