[package]
authors = [
    "Jorge Aparicio <jorge@japaric.io>",
    "Jonathan Pallant <github@thejpster.org.uk>",
]
description = "A heap allocator for Cortex-M processors"
documentation = "https://docs.rs/alloc-cortex-m"
keywords = [
    "arm",
    "cortex-m",
    "allocator",
]
license = "MIT OR Apache-2.0"
name = "alloc-cortex-m"
version = "0.3.4"

[dependencies]
cortex-m = "0.1.5"

[dependencies.linked_list_allocator]
default-features = false
version = "0.6.0"
